### ISSUE TITLE
Plugin should not fail 

### ISSUE THREAD

**Issue by ehmkah** [davidmc24/gradle-avro-plugin#107]
**Prerequisites**

* [X ] Are you running the latest version of the plugin? 
* [X ] Are you running a supported version of Gradle? 
* [X ] Are you running a supported version of Apache Avro? 
* [X ] Are you running a supported version of Java? 
* [X ] Did you check to see if an [issue](https://github.com/davidmc24/gradle-avro-plugin/issues) has already been submitted?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/davidmc24/gradle-avro-plugin/blob/master/CONTRIBUTING.md) guide.

**Describe the bug**

If I run the avro-plöugin for the example project (https://github.com/ehmkah/avro_poc) I get an error that a type is not supported. If I use the same sources and run the acro-tools against it, no error occurs. 

**To Reproduce**

1. Clone Project https://github.com/ehmkah/avro_poc 
2. Follow steps in the readme https://github.com/ehmkah/avro_poc/blob/master/README.adoc

**Expected behavior**

- Plugin should generate class files correctly
- A workaround might be to say the plugin in which order files should be read.

**Environment (please complete the following information):**
 - Gradle Version [e.g. 5.6.2]
 - Apache Avro Version [e.g. 1.9.2]
 - Gradle-Avro Plugin Version [e.g. 0.19.0]
 - Java Version [e.g.Java(TM) SE Runtime Environment (build 1.8.0_201-b09 ]
 - OS: [Ubuntu]

**Additional context**

**Comment by davidmc24** [comment]
@ehmkah Thank you for the bug report. I particularly appreciate including a full project to ease reproducing the failure. Assuming I can reproduce this, it seems likely that the exception thrown by the Avro compiler when simple hasn’t yet been compiled is slightly different with this schema, and a minor adjustment will allow it to be supported. If that’s the case, I’ll add support and test coverage, and should be able to push out a fixed version today.

**Comment by davidmc24** [comment]
Steps used attempting to reproduce:

1. Clone project
2. Fix Gradle wrapper (was missing `gradle/wrapper/gradle-wrapper.jar`)
3. Add some entries to `.gitignore` to cut down on noise (`.gradle/`, `build/`)
4. `./gradlew clean build --info` and saw that the failure wasn't occuring, since my system's traversal order was naturally doing Simple first.

Will try in a more controlled environment to try to capture the error.

**Comment by ehmkah** [comment]
Added you as a contributor to the repo just in case you want to commit your local fixes.

**Comment by davidmc24** [comment]
Thanks!  I think I can see how the error is different.  To enable better diagnosing this class of problems (schema dependency resolution failure due to different schema), I'm going to want to enhance the test support to allow testing the resolution in a particular order, and then add these files as a test case.  Updated timetable: hopefully some work tonight, and then a fixed release either over the weekend, or at worst, sometime next week.

**Comment by davidmc24** [comment]
Potential fix and test coverage added.  Now, to wait for the CI tests.

**Comment by davidmc24** [comment]
CI tests look good.  Planning to release version 0.19.1 later today.

**Comment by ehmkah** [comment]
As soon as the 0.19.1 plugin is release I am going to test it.

**Comment by davidmc24** [comment]
@ehmkah  0.19.1 released.  Please reply on this issue if you continue to encounter this problem after upgrading.
