### ISSUE TITLE
JCenter / Bintray Sunset

### ISSUE THREAD

**Issue by altery** [davidmc24/gradle-avro-plugin#133]
JCenter/Bintray will Sunset in May [1]. Is there an alternative repository where the plugin will be available in the future?

[1]: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by davidmc24** [comment]
Thank you for asking. This is the first I had heard of it.

A few possible options:

* start publishing to Maven Cental
* go back to the Gradle Plugin Portal (though they still don't provide adequate download statistics)
* adopt JFrog Platform Free for OSS (when they launch it)
* adopt GitHub Packages

**Comment by davidmc24** [comment]
I'll update here once I make a decision on direction.

**Comment by davidmc24** [comment]
I think that the Gradle Plugin Portal is still a no-go for me due to lack of progress on download statistics.  While I like the potential ease-of-publishing for GitHub Packages, it doesn't meet my ease-of-consumption standards, so it's out for the moment.  Artifactory Cloud for OSS isn't yet launched, and has no public timeline, so I'm not going to count on it.  Thus, I'm going to try to move forward with Maven Central.

I've submitted https://issues.sonatype.org/browse/OSSRH-64170 to request access to publish to the existing namespace.  If I can get it working, my plan is to re-publish all existing historical versions in the same namespace, under Maven Central.

If not, the fallback will be to establish a new namespace on Maven Central and publish just the new version, and store copies of historical versions elsewhere (maybe GitHub releases).

**Comment by davidmc24** [comment]
It's not going to be easy to get the same namespace on Maven Central, as the project is no longer CommerceHub-sponsored, and I don't own the domain.  New versions will be published to a new groupId (something under `com.github.davidmc24`) and I'll arrange something else to preserve historical versions.

**Comment by davidmc24** [comment]
GitHub Packages appears to be a poor option, even for historical versions, as it doesn't allow anonymous access.  You'd need to specify an access token.

https://github.community/t/download-from-github-package-registry-without-authentication/14407/92

**Comment by davidmc24** [comment]
All historical versions have been archived from JCenter and the Gradle Plugin Portal and made available via [GitHub Releases](https://github.com/davidmc24/gradle-avro-plugin/releases).  I don't really want to encourage people using out-of-date versions, and I suspect that many people who need to likely have access to a private Maven repo they can self-host in anyway.

Now that permanently losing access to historical release artifacts isn't an immediate concern, my next focus will be getting a new release up in Maven Central.

**Comment by davidmc24** [comment]
Documentation has been updated with information on how to find historical versions.

Version 1.0.0 has been released.  It has no functional changes beyond what was present in version 0.22.0, other than that it is now published to Maven Central, uses different plugin IDs, and uses a different package for the classes.

I **think** I've updated all the documentation appropriately.  If you happen to spot anything I missed, pull requests welcome.
