### ISSUE TITLE
Kotlin latest version compatibility

### ISSUE THREAD

**Issue by tituszban** [davidmc24/gradle-avro-plugin#207]
**Prerequisites**

N/A

**Describe the bug**

The [Compatibility section](https://github.com/davidmc24/gradle-avro-plugin#compatibility) of the README specifies Kotlin support up to 1.5.x. However, given the [publically known vulnorabilities](https://huntr.dev/bounties/e9b2b1dd-ab65-48e2-8042-b53253649961/) that are fixed in version 1.7.x, support for newer versions of kotlin would be beneficial, otherwise to avoid these issues people would need to use a different package.

I have done some very basic testing. All versions of 1.6.x are working fine, but I'm seeing issues on 1.7.x. This was nowhere near as comprehensive or thourough as any maintainer could do, hence it's probably pointless to provide details.

**Expected behavior**

Documented compatibility with the latest version of Kotlin.

**Comment by davidmc24** [comment]
It looks like you're correct that version 1.6.x should work, but 1.7.x is broken.  It looks like in 1.7.x, the Kotlin plugin decided to stop extending SourceTask.  Unfortunately, that would mean that to integrate, the Avro plugin would need to either depend on a specific version of the Kotlin plugin to compile, or use version-specific reflection, in order to access the right method to declare new sources.  I don't think that either of those are the right direction for this plugin.  Thus, in the next version of this plugin, I'll be dropping the Kotlin plugin integration logic, making it so that build authors can wire up the tasks as they see fit without this plugin getting in the way.  It would be possible to encapsulate that logic in a derived plugin, if desired.

**Comment by davidmc24** [comment]
Version 1.4.0 has been released.
