### ISSUE TITLE
Gnerating a Decimal value not working for java 

### ISSUE THREAD

**Issue by nabil86** [davidmc24/gradle-avro-plugin#215]
**Prerequisites**

* [x] Are you running the latest version of the plugin? (Check [releases](https://github.com/davidmc24/gradle-avro-plugin/releases))
* [x] Are you running a supported version of Gradle? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Apache Avro? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Java? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Did you check to see if an [issue](https://github.com/davidmc24/gradle-avro-plugin/issues) has already been submitted?
* [ ] Are you reporting to the correct repository?  If your schema doesn't work with the Apache Avro CLI tool either, it's not a problem with this plugin.  Running your file through the `CLIComparisonTest` in the sample project under the `test-project` directory can help diagnose this.
* [ ] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/davidmc24/gradle-avro-plugin/blob/master/CONTRIBUTING.md) guide.

**Describe the bug**
I'am using the latest version (1.5.0) and avro lib "1.11.1"

Given an avro containing a decimal fields:
` ....  {"name": "totalAmount",    "type": "bytes", "logicalType": "decimal"}, ....`
when i'am trying to generate a java class , i have this
`...
 private java.nio.ByteBuffer totalAmount; 
....`

**To Reproduce**

**Expected behavior**
 and i expect this
`
....
 private BigDecimal totalAmount;
....`

**Additional context**

**Comment by davidmc24** [comment]
Added a line to the end of `AvroPluginFunctionalSpec.can generate and compile java files from json schema` to verify that `BigDecimal` support is working correctly:

```
projectFile("build/generated-main-avro-java/example/avro/User.java").text.contains("BigDecimal salary")
```

If you had followed the instructions in the prerequisites above, you would have checked your schema against the CLI and found that the CLI generates the same output, indicating that the problem lies with your schema.

Here is the working format for `BigDecimal` support from my tests:

```
     {
         "name": "salary",
         "type": { "type": "bytes", "logicalType": "decimal", "precision": 4, "scale": 2 }
     },
```

Note the `type` for the field needs to be an object, which itself contains a type/logicalType/etc.
