### ISSUE TITLE
Would like support for AndroidStudio gradle plugin

### ISSUE THREAD

**Issue by dschmitt007** [davidmc24/gradle-avro-plugin#57]
Which doesn't seem to play nice with the java plugin

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > The 'java' plugin has been applied, but it is not compatible with the Android plugins.
   > Could not get unknown property 'javaPreCompileDebug' for project ':app' of type org.gradle.api.Project.

**Comment by davidmc24** [comment]
As I don't do Android development myself, I'm afraid the help I'm able to provide may be limited.

If you use the `com.commercehub.gradle.plugin.avro-base` plugin instead of the `com.commercehub.gradle.plugin.avro` plugin, it shouldn't require the "java" plugin, and will let you define Avro Java class generation tasks yourself.  Documentation of that feature is available here: https://github.com/commercehub-oss/gradle-avro-plugin#alternate-usage

I'm potentially open to including Android support in this plugin, but would need assistance to do so.  An example project showing what type of integration is desired would help.
