### ISSUE TITLE
Cannot import idl from external jar when the target has hierarchy

### ISSUE THREAD

**Issue by dmoneyUK** [davidmc24/gradle-avro-plugin#89]
When import idl from external dependency (jar, zip), it looks up the avro file as class file and always from the root path in the jar. As avro import use relative path, if the external jar has hierarchy, the importing fails.

**Example:**
| src/main/avro/importExternalProtocol (Local)
| classpath://external-avdl.jar (external jar)
-- external-avdl.jar?request.avdl
-- external-avdl.jar?common/ header.avdl
-- external-avdl.jar?common/ requestComponents.avdl

-  A local avdl import "request.avdl" from a external dependency:

```
@namespace("org.apache.avro")
protocol ImportExternalProtocol {
  import idl "request.avdl";

  record Imported {
      org.apache.avro.external.Request request;
  }
}
```

- The "request.avdl" in the external dependency imports "requestComponent.avdl" in a sub-folder "common\"
```@namespace("org.apache.avro.external")
protocol RequestProtocol {
  import idl "common/requestComponents.avdl";
  record Request {
    org.apache.avro.external.common.RequestComponents requestComponents;
    string body;
  }
}
```

- requestComponent.avdl import the "header.avdl" in the same folder
```@namespace("org.apache.avro.external.common")
protocol RequestComponentsProtocol {

    import idl "header.avdl";

    record RequestComponents {
        string method;
        org.apache.avro.external.common.Header header;
    }
}
```

When process import header.avdl, it fails as it try to import it from the root path in the jar.

I made a PR https://github.com/davidmc24/gradle-avro-plugin/pull/88 for the solution, it use a customized classloader to adjust the file path. A test is provided including a example external.jar. Would be great if I can contribute to the the plugin.

**Comment by davidmc24** [comment]
Thank you for the issue and pull request. 

I think I understand the problem and how the proposed change fixes it. However, isn’t this effectively a problem that any tool built using the Avro Java library would have, rather than something specific to this plugin?  If so, it would make more sense to submit it as a bug report to the Apache Avro project so that it can be fixed once in the upstream library, and then all other projects (such as this plugin, similar build plugins for other tools like Maven, etc.) can benefit.

**Comment by dmoneyUK** [comment]
Yes, you are right. I will give a try. The idl is implement in something JJ,  quite strange choice.
