### ISSUE TITLE
Multiple class with the same fully declared type could not be generated

### ISSUE THREAD

**Issue by Hakuhun** [davidmc24/gradle-avro-plugin#95]
Hi! 

If I'd like to generate from multiple schema files and those schemas are all containing a full description of an object - for example MessageContext - the generator will fail.

>  Found conflicting definition of type hu.****.*****.MessageContext in 

In our company we have to fully declare this object in every schema. So I don't know if it is a useage problem from our side and the generator implemented specificly this way.

**Comment by davidmc24** [comment]
That is an intentional behavior of this plugin.  It ensures that, if a nested type is defined in multiple schema files, the definition matches to avoid a potentially undesired result if a different variation is used last for source file generation.

You have two approaches you can take:

1. Make sure that the definitions of your nested types match exactly between all relevant schema files (the plugin will detect that they match and not treat it as an error)
2. Don't use files with multiple definitions of nested types, instead pulling the nested types out into their own files (ensuring that there is no ambiguity, as there is only a single definition of the type).
